# -*- coding: GBK -*-

# player states
PLAYER_STATE_IDLE = 1
PLAYER_STATE_MOVE = 2
PLAYER_STATE_DEAD = 3

# trap
TRAP_COST = 100
TRAP_RANGE = 10
TRAP_SPIKE_DAMAGE = 1

# map
MAP_EDGE_X = (-10)
MAP_EDGE_Z = 35
MAP_SIZE_X = 100
MAP_SIZE_Z = 250
MAP_ACCURATE = 0.2

# monster states
MONSTER_SPAWN_POINT = (20, 60)
MONSTER_DESTINATION = (220,60)

MONSTER_ATTACK_RANGE = 0.5
MONSTER_CHASE_RANGE = 5

MONSTER_STATE_IDLE = 1
MONSTER_STATE_MOVE = 2
MONSTER_STATE_CHASE = 3
MONSTER_STATE_ATTACK = 4
MONSTER_STATE_WIN = 5

MONSTER_DEATH_COIN = 50
MONSTER_DEATH_EXP = 100
MONSTER_SPEED_WALK = 2
MONSTER_SPEED_SLOW = 1

# Game round states
MONSTER_NUM_ROUND1 = 0



MSG_CS_LOGIN	= 0x1001
MSG_SC_GAMESTART    = 0x2001

MSG_CS_TRAPPLACE = 0x1003
MSG_SC_TRAPPLACE = 0x2006
MSG_SC_CONFIRM	= 0x2011
MSG_SC_NEWPLAYER = 0x2003
MSG_CS_MOVETO	= 0x1002
MSG_SC_MOVETO	= 0x2002
MSG_CS_BUY_TRAP = 0x1005

MSG_CS_MONSTER_DAMAGE = 0x1004
MSG_SC_NEWMONSTER = 0x2004
MSG_SC_MONSTER_MOVE = 0x2005
MSG_SC_MONSTER_STATE = 0x2007
MSG_SC_PLAYER_INFO = 0x2008
MSG_SC_MONSTER_DEATH = 0x2009

MSG_SC_ROUND_STATE = 0x2010
MSG_SC_GAME_RESET = 0x2012

NET_STATE_STOP	= 0				# state: init value
NET_STATE_CONNECTING	= 1		# state: connecting
NET_STATE_ESTABLISHED	= 2		# state: connected

NET_HEAD_LENGTH_SIZE	= 4		# 4 bytes little endian (x86)
NET_HEAD_LENGTH_FORMAT	= '<I'

NET_CONNECTION_NEW	= 0	# new connection
NET_CONNECTION_LEAVE	= 1	# lost connection
NET_CONNECTION_DATA	= 2	# data comming

NET_HOST_DEFAULT_TIMEOUT	= 70

MAX_HOST_CLIENTS_INDEX	= 0xffff
MAX_HOST_CLIENTS_BYTES	= 16

MAX_ENTITIS_INDEX = 0xffff
MAX_ENTITIS_BYTES = 16


