# -*- coding: GBK -*-

#s2c message type
LOGIN_RESPONSE = 1
REGISTER_RESPONSE = 2
MOVE_RESPONSE = 3
TRAP_RESPONSE = 4

#c2s message type
LOGIN_REQST = 1
REGISTER_REQST = 2
GAMESTART_REQST = 3
EVENT_REQST = 4

# c2s event type
EVENT_MOVE_REQST = 1
EVENT_DAMAGE_REQST = 2
EVENT_SYNC_REQST = 3

# s2c event type
EVENT_MOVE_SC = 1





# Cmd Type
CMD_UPDATE_PLAYER = 1

# player states
PLAYER_STATE_IDLE = 1
PLAYER_STATE_MOVE = 2
PLAYER_STATE_DEAD = 3

# trap
TRAP_RANGE = 2.0

# map
MAP_EDGE_X = 10
MAP_EDGE_Z = 35
MAP_SIZE_X = 50
MAP_SIZE_Z = 100
MAP_ACCURATE = 0.5

# monster states
MONSTER_SPAWN_POINT = (5,30)
MONSTER_DESTINATION = (0, -10)
MONSTER_CHASE_RANGE = 10
MONSTER_STATE_IDLE = 1
MONSTER_STATE_MOVE = 2
MONSTER_STATE_DEAD = 3
MONSTER_DEATH_COIN = 50
MONSTER_DEATH_EXP = 100

# Game round states

MONSTER_NUM_ROUND1 = 5
ENTITY_PLAYER = 1
ENTITY_MONSTER = 2

MSG_SC_UPDATE = 1

MSG_CS_LOGIN	= 0x1001
MSG_SC_LOGIN    = 0x2001

MSG_CS_TRAPPLACE = 0x1003
MSG_SC_TRAPPLACE = 0x2006
# MSG_SC_CONFIRM	= 0x2001
MSG_SC_NEWPLAYER = 0x2003
MSG_CS_MOVETO	= 0x1002
MSG_SC_MOVETO	= 0x2002

MSG_CS_MONSTER_DAMAGE = 0x1004
MSG_SC_NEWMONSTER = 0x2004
MSG_SC_MONSTER_MOVE = 0x2005
MSG_SC_MONSTER_STATE = 0x2007
MSG_SC_PLAYER_INFO = 0x2008
MSG_SC_MONSTER_DEATH = 0x2009

NET_STATE_STOP	= 0				# state: init value
NET_STATE_CONNECTING	= 1		# state: connecting
NET_STATE_ESTABLISHED	= 2		# state: connected

NET_HEAD_LENGTH_SIZE	= 4		# 4 bytes little endian (x86)
NET_HEAD_LENGTH_FORMAT	= '<I'

NET_CONNECTION_NEW	= 0	# new connection
NET_CONNECTION_LEAVE	= 1	# lost connection
NET_CONNECTION_DATA	= 2	# data comming

NET_HOST_DEFAULT_TIMEOUT	= 70

MAX_HOST_CLIENTS_INDEX	= 0xffff
MAX_HOST_CLIENTS_BYTES	= 16

MAX_ENTITIS_INDEX = 0xffff
MAX_ENTITIS_BYTES = 16
